"""Add summary column to news table

Revision ID: 0d6c3e8d663c
Revises: 06357e4ad6e7
Create Date: 2025-10-01 19:29:48.988579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6c3e8d663c'
down_revision: Union[str, Sequence[str], None] = '06357e4ad6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('summary', sa.Text(), nullable=True, comment='Resumo ou descrição da notícia.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'summary')
    # ### end Alembic commands ###
